server:
  num_rounds: 10
  zscore_threshold: 2.5
  momentum: 0.9
  server_address: "0.0.0.0:8080"
  dataset_type: 'traditional'
  model_type: 'image'
  input_column: 'img'
  output_column: 'label'
  input_shape: [32, 32, 3]
  num_classes: 10
client1:
  dataset_name: 'uoft-cs/cifar10'
  dataset_type: 'traditional'
  model_type: 'image'
  input_column: 'img'
  output_column: 'label'
  input_shape: [32, 32, 3]
  num_classes: 10
client2:
  dataset_name: 'wasifis/image-10'
  dataset_type: 'traditional'
  model_type: 'image'
  input_column: 'img'
  output_column: 'label'
  input_shape: [32, 32, 3]
  num_classes: 10